!ArenaConfig
arenas:
  0: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  1: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  2: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  3: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  4: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  5: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  6: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  7: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  8: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  9: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  10: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  11: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  12: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  13: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  14: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  15: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  16: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  17: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  18: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  19: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  20: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  21: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  22: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  23: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
  24: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
