!ArenaConfig
arenas:
  0: !Arena
    t: 500
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 22, y: 0, z: 20}
      - !Vector3 {x: 18, y: 0, z: 20}
      rotations: [45, 135]
      colors:
      - !RGB {r: 204, g: 0, b: 204 }
      - !RGB {r: 204, g: 0, b: 204 }
      sizes:
      - !Vector3 {x: 5, y: 1, z: 1}
      - !Vector3 {x: 5, y: 1, z: 1}
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal

      
