!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
  1: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
  2: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
  3: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
