name: animalai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.*
  - pip
  - pillow>=4.2.1,<=5.4.1
  - numpy>=1.13.3,<=1.14.5
  - protobuf>=3.6,<3.7
  - grpcio>=1.11.0,<1.12.0
  - pyyaml>=5.1
  - jsonpickle>=1.2
  - pyglet>=1.2.0
  - scipy
  - cloudpickle=1.2.*
  - future
  - pip:
    - gym
    - animalai

