!ArenaConfig
arenas:
  0: !Arena
    t: 500
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 17.958857161731096, y: 0, z: 32.24444369716801}
      - !Vector3 {x: 12.958857161731094, y: 0, z: 32.24444369716801}
      - !Vector3 {x: 22.041142838268907, y: 0, z: 32.24444369716801}
      - !Vector3 {x: 27.041142838268907, y: 0, z: 32.24444369716801}
      - !Vector3 {x: 15.0, y: 0, z: 12.5}
      - !Vector3 {x: 25.0, y: 0, z: 12.5}
      - !Vector3 {x: 20, y: 1, z: 12.5}
      sizes:
      - !Vector3 {x: 15, y: 7, z: 0.2}
      - !Vector3 {x: 15, y: 7, z: 0.2}
      - !Vector3 {x: 15, y: 7, z: 0.2}
      - !Vector3 {x: 15, y: 7, z: 0.2}
      - !Vector3 {x: 0.2, y: 7, z: 25}
      - !Vector3 {x: 0.2, y: 7, z: 25}
      - !Vector3 {x: 9.5, y: 0.5, z: 24.5}
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      rotations: [75.0, 75.0, 105.0, 105.0, 0, 0, 0]
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 26.382285676537812, y: 0, z: 38}
    - !Item
      name: BadGoal
      positions:
      - !Vector3 {x: 13.617714323462188, y: 0, z: 38}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 1.5, z: 1}
      rotations: [0]